import type { ConfigSection } from '../core/ConfigManager';

export const animationConfig: ConfigSection = {
  id: 'animation',
  label: 'Animation',
  fields: [
    {
      key: 'enabled',
      label: 'Procedural FX',
      type: 'boolean',
      defaultValue: true,
    },
    // -- walk framerate scaling --
    {
      key: 'walkFpsMin',
      label: 'Walk FPS Min',
      type: 'number',
      min: 2,
      max: 8,
      step: 1,
      defaultValue: 4,
    },
    {
      key: 'walkFpsMax',
      label: 'Walk FPS Max',
      type: 'number',
      min: 6,
      max: 16,
      step: 1,
      defaultValue: 12,
    },
    // -- idle breathing --
    {
      key: 'breathSpeed',
      label: 'Breath Speed',
      type: 'number',
      min: 0.5,
      max: 4,
      step: 0.1,
      defaultValue: 0.9,
    },
    {
      key: 'breathScaleAmt',
      label: 'Breath Scale',
      type: 'number',
      min: 0,
      max: 0.05,
      step: 0.002,
      defaultValue: 0.012,
    },
    {
      key: 'breathBobAmt',
      label: 'Breath Bob (px)',
      type: 'number',
      min: 0,
      max: 4,
      step: 0.25,
      defaultValue: 1,
    },
    // -- walk bob --
    {
      key: 'walkBobAmt',
      label: 'Walk Bob (px)',
      type: 'number',
      min: 0,
      max: 6,
      step: 0.25,
      defaultValue: 0.6,
    },
    // -- stop settle --
    {
      key: 'settleStiffness',
      label: 'Settle Stiffness',
      type: 'number',
      min: 100,
      max: 2000,
      step: 50,
      defaultValue: 600,
    },
    {
      key: 'settleDamping',
      label: 'Settle Damping',
      type: 'number',
      min: 2,
      max: 30,
      step: 1,
      defaultValue: 12,
    },
    {
      key: 'settleKick',
      label: 'Settle Kick',
      type: 'number',
      min: 0,
      max: 200,
      step: 5,
      defaultValue: 60,
    },
    // -- squash/stretch --
    {
      key: 'squashIntensity',
      label: 'Squash Intensity',
      type: 'number',
      min: 0,
      max: 0.3,
      step: 0.01,
      defaultValue: 0.06,
    },
    {
      key: 'squashRecovery',
      label: 'Squash Recovery',
      type: 'number',
      min: 2,
      max: 20,
      step: 1,
      defaultValue: 8,
    },
    // -- lean --
    {
      key: 'leanFactor',
      label: 'Lean Factor',
      type: 'number',
      min: 0,
      max: 0.05,
      step: 0.005,
      defaultValue: 0.03,
    },
    {
      key: 'leanSmoothing',
      label: 'Lean Smoothing',
      type: 'number',
      min: 2,
      max: 20,
      step: 1,
      defaultValue: 6,
    },
    // -- pickup --
    {
      key: 'pickupFlyDuration',
      label: 'Pickup Fly (ms)',
      type: 'number',
      min: 100,
      max: 500,
      step: 25,
      defaultValue: 250,
    },
  ],
};
