import type { ConfigSection } from '../core/ConfigManager';

/** Lamp tuning: fuel capacity, burn rate, starting fuel, refuel amounts. */
export const lampConfig: ConfigSection = {
  id: 'lamp',
  label: 'Lamp',
  fields: [
    {
      key: 'maxFuel',
      label: 'Max Fuel',
      type: 'number',
      min: 10,
      max: 300,
      step: 5,
      defaultValue: 100,
    },
    {
      key: 'startingFuel',
      label: 'Starting Fuel',
      type: 'number',
      min: 5,
      max: 300,
      step: 5,
      defaultValue: 100,
    },
    {
      key: 'burnRate',
      label: 'Burn Rate (fuel/sec)',
      type: 'number',
      min: 0.5,
      max: 20,
      step: 0.5,
      defaultValue: 3,
    },
    {
      key: 'fuelPerPickup',
      label: 'Fuel per Pickup',
      type: 'number',
      min: 1,
      max: 50,
      step: 1,
      defaultValue: 15,
    },
    {
      key: 'criticalThreshold',
      label: 'Critical % (flicker)',
      type: 'number',
      min: 0.05,
      max: 0.5,
      step: 0.05,
      defaultValue: 0.2,
    },
    {
      key: 'glowRadiusMax',
      label: 'Glow Radius (full)',
      type: 'number',
      min: 50,
      max: 800,
      step: 10,
      defaultValue: 200,
    },
    {
      key: 'glowRadiusMin',
      label: 'Glow Radius (empty)',
      type: 'number',
      min: 10,
      max: 150,
      step: 5,
      defaultValue: 40,
    },
    {
      key: 'glowColor',
      label: 'Glow Warmth',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 0.3,
    },
    {
      key: 'glowColorName',
      label: 'Lamp Color',
      type: 'choice',
      options: [
        { value: 'default', label: 'Default (Amber)' },
        { value: 'blue', label: 'Blue' },
        { value: 'purple', label: 'Purple' },
        { value: 'orange', label: 'Orange' },
      ],
      defaultValue: 'default',
    },
    {
      key: 'darknessAlpha',
      label: 'Darkness Opacity',
      type: 'number',
      min: 0.5,
      max: 1,
      step: 0.05,
      defaultValue: 0.92,
    },
  ],
};
